name: simple_notes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.9.3
  device_preview: ^1.1.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  flutter_tts: ^3.8.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
