name: simple_notes
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.9.3
  expandable_menu: ^0.0.5
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
